language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
dist: trusty
sudo: true
install: true
branches:
  only:
  - master
script:
  - env GO111MODULE=on go build
before_deploy:
  - go run main.go
  - cp README.md docker
  - cp LICENSE docker
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUBTOKEN 
  keep-history: true
  target-branch: master
  local_dir: docker
  repo: satishbabariya/swift-snapshots-docker
  email: satish.babariya@gmail.com
  name: Satish Babariya